site_name: Machine Learning Basics
extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
markdown_extensions:
    - mdx_math
theme: readthedocs
pages:
- Home: index.md
- Database Basics: db/db.md
- Data Preprocessing: preprocess/data_preprocessing.md
- Algorithm: algorithm/algorithm.md
- Machine Learning Framework: framework/framework.md
- Big Data: bigdata/bigdata.md





